json.id invite.id
json.user_id invite.user_id
json.invitee_id invite.invitee_id
json.restaurant_id invite.restaurant_id
json.status invite.status
json.show invite.showing
json.hidden !invite.showing
json.payment_preference invite.payment_preference
json.channel_name invite.channel_name
json.channel_group invite.user.reload.channel_group
json.created_at invite.created_at
