default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: "dineconnect_dev"

test:
  <<: *default
  database: "dineconnect_test"

production:
  url: <%= ENV.fetch('DATABASE_URL', "").sub(/^postgres/, "postgis") %>
  pool: <%= ENV['MAX_THREADS'] || 5 %>
  timeout: 5000
